version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'github-actions'
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/examples/'
    schedule:
      interval: 'daily'
    groups:
      regular:
        update-types:
          - 'minor'
          - 'patch'
    labels:
      - 'dependencies'
    versioning-strategy: increase
