version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'github-actions'
  - package-ecosystem: 'npm'
    directories:
      - '/'
    schedule:
      interval: 'daily'
    groups:
      regular:
        update-types:
          - 'patch'
          - 'minor'
        exclude-patterns:
          - 'typescript'
      typescript:
        update-types:
          - 'patch'
          - 'minor'
          - 'major'
        patterns:
          - 'typescript'
      typescript-eslint:
        update-types:
          - 'major'
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint/*'
      size-limit:
        update-types:
          - 'major'
        patterns:
          - 'size-limit'
          - '@size-limit/*'
      eslint:
        update-types:
          - 'major'
        patterns:
          - 'eslint'
          - '@eslint/*'
    labels:
      - 'dependencies'
    versioning-strategy: increase
