name: Test
on: [push, pull_request]

jobs:
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 18
          - 20
          - 22
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Type check
        if: matrix.node-version == 20
        run: pnpm typecheck

      - name: Lint
        if: matrix.node-version == 20
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test
        env:
          FORCE_COLOR: 2

      - name: Run examples
        run: cd examples && pnpm run all
